'''

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

'''

def generate_triangle_numbers(number):
    triangle_numbers = []
    for x in range(number):
        l = list(range(x))
        triangle_numbers.append(sum(l))
    return triangle_numbers


def check_divisors(triangle_number):
    divisors = []
    for x in range(1,int(triangle_number**0.5)+1):
        if triangle_number % x == 0:
            divisors.append(x)
            divisors.append(x)
    return divisors

def run(number_triangles, divisor_number):
    triangle_numbers = generate_triangle_numbers(number_triangles)
    c = 0
    divisors = []
    res = 0
    while len(divisors) < divisor_number:
        triangle = triangle_numbers[c]
        divisors = check_divisors(triangle)
        res = triangle
        c+=1
    return res

if __name__ == '__main__':

    test = run(10,5)
    print(f"result test: {test}")

    real = run(15000,500)
    print(f"result: {real}")